### ISSUE TITLE
Increasing pool of results

### ISSUE THREAD

**Issue by billbogaiv** [khalidabuhakmeh/madlibs#1]
Is not `Random.Next(int, int)` `(inclusive, exclusive)` respectfully? https://github.com/khalidabuhakmeh/madlibs/commit/306e1599285c5821625352fc9248b2dce387a9cd#diff-a87bb9ba0046ac9a9d9c27f664df7bd5R37 reduces the upper-bound by one.

**Comment by khalidabuhakmeh** [comment]
Fixed. 

![](https://media4.giphy.com/media/72ouzZHKYarf2/giphy.gif)
